name: Deploy Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: eu-north-1

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.6"

      - name: Terraform init
        run: terraform init
        working-directory: infra

      - name: Terraform apply
        run: terraform apply -auto-approve
        working-directory: infra
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
          TF_VAR_jwt_secret:  ${{ secrets.JWT_SECRET }}

      - name: Print outputs
        run: terraform output
        working-directory: infra
